# number of sensors
number_of_sensors: 5
#number_of_sensors: 10

# maximal sensor range
max_sensor_range: 30.0 # in [m]
#max_sensor_range: 4.0 # in [m]

# opening angles for the sensors
open_angle_1: 1.5708 # (=90*PI/180 deg) in [rad]
open_angle_2: 0.0 # in [rad]

# maximal allowed linear velocity for each sensor
max_linear_sensor_velocity: 10.5 # in [m/s]
#max_linear_sensor_velocity: 1.5 # in [m/s]

# maximal allowed angular velocity for each sensor
max_angular_sensor_velocity: 0.5236 # (=30*PI/180) in [rad/s]

# number of particles for PSO
number_of_particles: 10

# maximal number of iterations for PSO
max_num_iterations: 400

# minimal coverage to stop the PSO algorithm
min_coverage_to_stop: 0.95

# PSO parameters for updating the particles
# parameter for the initial velocity part
c1: 0.729
# parameter for the personal best velocity part
c2: 1.49445
# parameter for the global best velocity part
c3: 1.49445

# parameter for offset between two targets in Greedy Search Algorithm
GS_target_offset: 5.3 # in [m]

# opening angles for a single slice of sensor FOV (for sensor's orientation search optimization)
slice_open_angle_1: 0.26180 # (=15*PI/180 deg) in [rad]
slice_open_angle_2: 0.0 # in [rad]
